Repository Aeliot-Tm/php-cs-fixer-baseline, pull requests merged in 2024-10, with the labels that each got.

#36 Add configuration reader and configuration dir argument
  README.md
  bin/pcsf-baseline
  docker-entrypoint.sh
  src/Service/ConsoleOptionsReader.php
  tests/Unit/Functional/CommandLineTest.php
  tests/config/.php-cs-fixer-baseline.json
  tests/config/.php-cs-fixer-finder.php
  tests/config/.php-cs-fixer.dist.php
Labels: enhancement

#41 Fix code style
  bin/pcsf-baseline
  src/Service/ConsoleOptionsReader.php
  tests/Unit/Functional/CommandLineTest.php
Labels: code_quality

#43 #40 config registration of TODOs as issues
  .github/workflows/todo-registrar.yaml
Labels: CI/CD

#46 Change key
  .github/workflows/release.yaml
  README.md
Labels: bug, contribution, CI/CD

#47 Install TODO Registrar
  .github/workflows/todo-registrar.yaml
  .phive/phars.xml
  .phive/trust-gpg-keys.txt
Labels: CI/CD

#48 #40 Fix path to TODO Registrar PHAR
  .phive/phars.xml
Labels: bug, CI/CD

#49 #40 Add config for TODO Registrar
  scripts/todo-registrar/config.php
Labels: bug, CI/CD

#50 #40 Don't create PR when nothing was commited
  .github/workflows/todo-registrar.yaml
Labels: CI/CD

#53 Move configs of PHPStan to scripts directory
  composer.json
  scripts/phpstan/baseline.neon
  scripts/phpstan/config.neon
Labels: CI/CD, code_quality

#54 Move configs of PHPUnit to scripts directory
  .gitignore
  composer.json
  scripts/phpunit/config.xml
Labels: CI/CD

#55 Move config of PHP CS Fixer to ./scripts directory
  .php-cs-fixer-finder.php
  composer.json
  scripts/php-cs-fixer/baseline.json
  scripts/php-cs-fixer/config.php
  scripts/php-cs-fixer/finder.php
Labels: CI/CD, code_quality

#57 Add code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: contribution

#58 Add contributing notes
  .github/CONTRIBUTING.md
Labels: contribution
